# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

env:
  global:
    - GO111MODULE=on

cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

install:
  - sudo apt-get install ocl-icd-opencl-dev
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable

jobs:
  include:
    - language: go
      go: 1.14.x
      name: "Linter"
      script:
        - make lint
    - language: go
      go: 1.14.x
      name: "Test"
      script:
        - make test
